version: 1.0.{build}
build:
  verbosity: minimal

artifacts:
  - path: setup.iss 
  
deploy:
- provider: GitHub
  tag: Chat-v$(appveyor_build_version)
  release: Chat-v$(appveyor_build_version)
  description: Release description
  auth_token:
    secure: p8nPg/ZAPy+a9Kx1ZEAuECSWT4ywolGOGoyiuZonc5kgvD/sT/YD9F7DD/CdgQTu
  artifact: setup.iss
  draft: true
  prerelease: false
  on:
    branch: master
